// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSession = "session"

// Session mapped from table <session>
type SessionMigration struct {
	SessionID string `gorm:"column:session_id;primaryKey" json:"session_id"`
	UserID    int32  `gorm:"column:user_id" json:"user_id"`
	CreatedAt int64  `gorm:"column:created_at" json:"created_at"`
	ExpiresAt int64  `gorm:"column:expires_at" json:"expires_at"`
	Agent     string `gorm:"column:agent" json:"agent"`
}

// TableName Session's table name
func (*SessionMigration) TableName() string {
	return TableNameSession
}

type Session struct {
	SessionID string `gorm:"column:session_id;primaryKey" json:"session_id"`
	UserID    int32  `gorm:"column:user_id" json:"user_id"`
	CreatedAt int64  `gorm:"column:created_at" json:"created_at"`
	ExpiresAt int64  `gorm:"column:expires_at" json:"expires_at"`
	Agent     string `gorm:"column:agent" json:"agent"`
	User      User   `gorm:"foreignKey:UserID"`
}
