// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "errors"

const TableNameUsersFile = "users_files"

const (
	RoleOwner        = "Owner"
	RoleCollaborator = "Collaborator"
)

// UsersFile mapped from table <users_files>
type UsersFileMigration struct {
	UserID int32  `gorm:"column:user_id;primaryKey;not null" json:"user_id"`
	FileID int32  `gorm:"column:file_id;primaryKey;not null" json:"file_id"`
	Role   string `gorm:"column:role;default:Collaborator" json:"role"`
}

// TableName UsersFile's table name
func (*UsersFileMigration) TableName() string {
	return TableNameUsersFile
}

func (uf *UsersFileMigration) Validate() error {
	switch uf.Role {
	case RoleOwner, RoleCollaborator:
		return nil
	default:
		return errors.New("role must be Owner or Collaborator")
	}
}

type UsersFile struct {
	UserID int32  `gorm:"column:user_id;primaryKey;not null" json:"user_id"`
	FileID int32  `gorm:"column:file_id;primaryKey;not null" json:"file_id"`
	Role   string `gorm:"column:role;default:Collaborator" json:"role"`
	File   File   `gorm:"foreignKey:FileID"`
	User   User   `gorm:"foreignKey:UserID"`
}
